### ISSUE TITLE
Can I set 'isolation_level' as 'READ UNCOMMITTED'?

### ISSUE THREAD

**Issue by Beomi** [michiya/django-pyodbc-azure#137]
Currently I'm working on large-scale Database which should not be 'locked' when read(SELECT) query.

On [Django's MySQL option](https://docs.djangoproject.com/en/2.0/ref/databases/#mysql-isolation-level) there is 'isolation_level' option for select isolation level for each db settings.

Can I use these options for MS-SQL too? like this:

```python
'MSSQL': {
    'NAME': 'dbname',
    'ENGINE': 'sql_server.pyodbc',
    'HOST': 'ipip',
    'USER': 'user',
    'PASSWORD': 'password1234',
    'OPTIONS': {
        'isolation_level': 'READ UNCOMMITTED', # like this
    },
},
```

**Comment by shaib** [comment]
"READ UNCOMMITTED" means you want to be able to read database changes before transactions end. It means you are not interested in the atomicity of transactions. If this is truly the case, you should probably not have transactions at all (other than the single-statement transactions provided by auto-commit mode). If you are interested in transactions, then READ UNCOMMITTED is only appropriate in very exceptional cases, and just avoiding some locks is not one of them.

Further,  It's been a while since I played much with SQL Server, but as far as I know reading records does not lock them under the default, READ COMMITTED isolation level.

**Comment by michiya** [comment]
There seem to be some other requests for dirty reads (#82) so I have added the feature in the same way as the other Django database backends (041e85f). It will be pushed to PyPI soon.

**Comment by michiya** [comment]
The feature is included in the latest release and now you can specify isolation_level in your database settings. See README for more details.
