### ISSUE TITLE
Ubuntu + FreeTDS + Django 2.0.1: The database driver doesn't support modern datatime types.

### ISSUE THREAD

**Issue by Belval** [michiya/django-pyodbc-azure#142]
Hi!

I installed Django 2.0.1 (and the matching django-pyodbc-azure package) on Ubuntu.

I am greated with this:

    File "/var/www/belval/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
    File "/var/www/belval/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
    File "/var/www/belval/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
    File "/var/www/belval/env/lib/python3.5/site-packages/django/db/backends/base/base.py", line 196, in connect
    self.init_connection_state()
    File "/var/www/belval/env/lib/python3.5/site-packages/sql_server/pyodbc/base.py", line 359, in init_connection_state
    "The database driver doesn't support modern datatime types.")
django.core.exceptions.ImproperlyConfigured: The database driver doesn't support modern datatime types.

Everything worked with Django 1.10.7.

Thank you!

**Comment by michiya** [comment]
django-pyodbc-azure 2.0 requires TDS protocol 7.3 at minimum because it doesn't support the legacy datetime type anymore (#109).
I guess you can resolve the issue by setting `tds version` for your database to 7.3 or newer in your freetds.conf if you have FreeTDS 0.95 or newer.
http://www.freetds.org/userguide/freetdsconf.htm

**Comment by Belval** [comment]
I am not at work anymore, but I will be testing this as soon as possible.

Do you mind if I leave the issue open until then?

Thank you for your time!

**Comment by justinsg** [comment]
+1 this solved it for me.

I upgraded to FreeTDS 1.00.80 and changed `freetds.conf` to use `tds version = 7.4`.

Unfortunately the Ubuntu repositories [only have 0.91](https://bugs.launchpad.net/ubuntu/+source/freetds/+bug/1679975) so I built the latest release from the FreeTDS website. It's up on my PPA for anyone to use: https://launchpad.net/~justinstandring/+archive/ubuntu/freetds . The sources are up there too so you can verify which release I used.

**Comment by Belval** [comment]
Custom package did not work and the version of FreeTDS I built was throwing error about a dynamic library missing. I decided to cut my losses and use Microsoft ODBC Driver. I thank you for your time.

**Comment by spyoungtech** [comment]
I encountered this issue and it turned out to be a configuration issue the led the wrong driver to be used with `pyodbc.connect` when using a DSN.

Upon investigation, I found `SQLSRV32.DLL` was always incorrectly bring used as the driver, despite my configuration specifying the ODBC driver. I hand-patched in my own connection string in the `get_new_connection` method and the error went away and the driver was the appropriate `MSODBCSQL` dll.

As it turns out, when you specify the dsn option, the 'driver' option from the configuration is ignored entirely. For some unknown reason, the driver specified in my DSN file was not being used. The ultimate solution appears to be to simply not use a DSN connection and provide all the options for the connection manually via the 'extra_params' option.

**Comment by ptchankue** [comment]
Hi there! 

I am experiencing a similar issue. Everything used to work when I was using Django 1.10.4. Now I am using Django 2.1.2, FreeTDS 1. 00.80, TDS Version=7.4, Python 3.5
pyodbc==4.0.24
django-pyodbc-azure==2.1

I manage to connect directly from the shell using `pyodbc.connect`, but from Django I am getting
`django.core.exceptions.ImproperlyConfigured: The database driver doesn't support modern datatime types.`

Can you please assist?

Regards,

**Comment by kevin-olbrich** [comment]
You can't use FreeTDS anymore. You must use MS-ODBC drivers:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

For me, the MS-ODBC driver is working perfectly. Even better then FreeTDS.

**Comment by ptchankue** [comment]
Ok thank you for the advice. Could you perhaps point me to a documentation of how to set it up? The link that you sent only explains how to install it.

**Comment by kevin-olbrich** [comment]
Thats very easy, just install the package as described in the link above and set:
```
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
```

I use the v17 package which also works fine with older SQL server releases (at least for me).
If you use the v13 package, just change 17 to 13 in the code above.

The string is the same on windows and linux, which also is very convenient.

The driver entry in unixODBC will be added automagically during package install.

**Comment by ptchankue** [comment]
Hi Kevin,
Thank you for the advise. I have implemented it and change the odbc.ini accordingly. But trying to connect using 
`cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=MYSERVER;PORT=1433;DATABASE=MYDB;UID=DOMAIN\\User;PWD=****')` I get the error:

`pyodbc.InterfaceError: ('28000', "[28000] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'DOMAIN\\User`

I still have FreeTDS installed, when I use `DRIVER=FreeTDS` it works fine.

What am I doing wrong?
