### ISSUE TITLE
CommandError: Unable to serialize database: 'unicode' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by sivaa** [michiya/django-pyodbc-azure#15]
The dumpdata command fails with the following error when the given Model has DateField()

Model Field:

```
registered_date      =   models.DateField()
```

Command Used:

```
python manage.py dumpdata our_app.Model
```

Error Received

```
CommandError: Unable to serialize database: 'unicode' object has no attribute 'isoformat'
```

**Comment by michiya** [comment]
Thank you for reporting. Could you give me the error traceback adding `--traceback` option to the command?

**Comment by sivaa** [comment]
Here is the traceback details.

```
(macro) D:\Python\ws\macro\macro>python manage.py dumpdata myapp.MyModel --settings=macro.local_settings --traceback
[Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Python\envs\macro\lib\site-packages\django\core\management\__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "D:\Python\envs\macro\lib\site-packages\django\core\management\__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Python\envs\macro\lib\site-packages\django\core\management\base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "D:\Python\envs\macro\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "D:\Python\envs\macro\lib\site-packages\django\core\management\commands\dumpdata.py", line 135, in handle
    use_natural_keys=use_natural_keys, stream=self.stdout)
  File "D:\Python\envs\macro\lib\site-packages\django\core\serializers\__init__.py", line 122, in serialize
    s.serialize(queryset, **options)
  File "D:\Python\envs\macro\lib\site-packages\django\core\serializers\base.py", line 50, in serialize
    self.handle_field(obj, field)
  File "D:\Python\envs\macro\lib\site-packages\django\core\serializers\python.py", line 51, in handle_field
    self._current[field.name] = field.value_to_string(obj)
  File "D:\Python\envs\macro\lib\site-packages\django\db\models\fields\__init__.py", line 808, in value_to_string
    return '' if val is None else val.isoformat()
AttributeError: 'unicode' object has no attribute 'isoformat'
```

**Comment by michiya** [comment]
Thank you for the additional information. 

I guess you are using `SQL Server` ODBC Driver (sqlsrv32.dll) for your database driver and that's why you receive the error. Django serializer needs to receive DateField values as date type, but in your case SQL Server converts the value from date to varchar type automatically because the driver doesn't understand the date type.

`SQL Server` ODBC Driver is basically for old versions of SQL Server and is obsolete to work with new versions of SQL Server. If you want to make use of new features, for example new data types like date, you have to use the appropriate version of `SQL Server Native Client` instead. If you want to know more about the difference between `SQL Server` ODBC Driver and `SQL Server Native Client`, see this:
http://blogs.msdn.com/b/sqlnativeclient/archive/2008/02/27/microsoft-sql-server-native-client-and-microsoft-sql-server-2008-native-client.aspx

Anyway, I think a quick and reliable solution for your problem is just to install `SQL Server Native Client` (or more recent `Microsoft ODBC Driver 11 for SQL Server`) on your computer and specify the driver name as `driver` option in your DATABASE settings.

**Comment by walkingonbothsides** [comment]
Hi,

I'm facing the same issue. I'm on a Linux  machine using FreeTDS and unixODBC.

Any ideas, how to resolv it? Everything works as it should except `dumpdata`.

**Comment by michiya** [comment]
@GordonFreemem As far as I understand, this issue could be seen only on Windows and is already fixed in ce785d1. Could you tell me what SQL data type is assigned for the date field on your model table?

**Comment by walkingonbothsides** [comment]
Of course, I did test a few things to reproduce the error:

I habe a field like `birthday = models.DateField(blank=True, null=True)`. On my dev machine with sqlite everything is ok. On my test and prod machines, both with SQLServer I can reproduce the error by setting a date. If I remove all dates from the model (so every entry is NULL), the dump works.

The data type on the SQLServer-side is `date`.

SQLServer-Version ist

```
SELECT @@VERSION
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
    Aug 19 2014 12:21:34 
    Copyright (c) Microsoft Corporation
    Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

**Comment by michiya** [comment]
@GordonFreemem Thank you for the details.

> The data type on the SQLServer-side is date.

That's why dumpdata fails on your Linux machine. FreeTDS supports TDS protocol versions up to 7.2 and can't handle `date` type, and SQL Server converts a `date` value to a `varchar` value automatically when you retrieve it via FreeTDS. See this for the differences between TDS protocol versions:
http://www.freetds.org/userguide/choosingtdsprotocol.htm

But I wonder why the `date` type is assigned to the DateField because the backend usually assigns the legacy `datetime` type to a DateField when you run migrations using FreeTDS. Did you perhaps apply migrations from a Windows machine?

**Comment by walkingonbothsides** [comment]
OK, I see the issue. As far as I remember I did start the project using `django-pyodbc` and switched to `django-pyodbc-azure` because I couldn't make it work with Django 1.7. So I assume `django-pyodbc` created the date-field and since I didn't need the dumpdata until now I did not notice it.

My freetds/unixODBC config is configured for protocol version 8.0. As your link says, that means it is using version 7.1. Since we have SQLServer 2008 I tried switching to 7.3, but now I get an error on every SQL-request `('42000', '[42000] [FreeTDS][SQL Server]Unicode data in a Unicode-only collation or ntext data cannot be sent to clients using DB-Library (such as ISQL) or ODBC version 3.7 or earlier. (4004) (SQLExecDirectW)')`.
:-/

How do I solve this? Maybe changing the `date`-field to `datetime` manually in SQL Management Studio? Or could this result in more problems.

~~Do you have an idea on how to resolv the error with protocoll version 7.3?~~
[EDIT]: The second question I managed to answer myself. It seems, that freetds supports SQLServer 2008 (and protocol version 7.3) since version 0.95. I'm running 0.91 on both machines.. So I have to wait until this release shows up in the main repositories of rhel/debian.

Thank you for your support.

**Comment by GordonFreemem** [comment]
The second question I managed to answer myself. It seems, that freetds supports SQLServer 2008 (and protocol version 7.3) since version 0.95. I'm running 0.91 on both machines.. So I have to wait until this release shows up in the main repositories of rhel/debian.

**Comment by michiya** [comment]
> How do I solve this? Maybe changing the date-field to datetime manually in SQL Management Studio? 

@GordonFreemem You'll be able to dump the table by doing that. If you have created your tables without using django-pyodbc-azure, I also recommend that you remove those tables and create them again running migrations with django-pyodbc-azure to eliminate potential incompatibilties between the tables and the backend.

**Comment by walkingonbothsides** [comment]
Hi,

I tried to manually alter the field directly with sql and it seemed to work. At least I'm able to dumpdata now. I will test my test-environment before doing this in prod.

Since I intend to upgrade the OS on my prod system I will dump the data and recreate the table with django-pyodbc-azure as you mentioned.

Thank you again for your help.

**Comment by michiya** [comment]
@GordonFreemem You're welcome and I'm glad to know that you finally succeeded in dumping the table:)
