### ISSUE TITLE
Required Django version

### ISSUE THREAD

**Issue by wil** [michiya/django-pyodbc-azure#170]
Hello,

Currently, django-pyodbc-azure 2.0.6.* requires django >= 2.0.6.
Is there any reason why it could not relax the required django version to `>=2.0` ? That way, we do not have to force developers to upgrade Django.

**Comment by michiya** [comment]
django-pyodbc-azure 2.0.6 is incompatible with Django 2.0.4 or earlier because it relies on the codes introduced from Django 2.0.5 such as the following.
https://github.com/django/django/blob/2.0.5/django/db/backends/base/schema.py#L17-L30

Basically django-pyodbc-azure has depenency on the latest version of Django at the time of its publication.
A new version of Django usually contains security fixes and Django developers encourage users to upgrade their Django installation to the latest one as soon as possible like this. 
https://www.djangoproject.com/weblog/2018/aug/01/security-releases/

django-pyodbc-azure is also tested only on the latest secure version of Django complying with recommendations like above ones and I don't bother to make sure that the latest django-pyodbc-azure works well with old insecure versions of Django. That's why django-pyodbc-azure requires the latest versions of Django as of its release date.

**Comment by wil** [comment]
Hi @michiya, thanks for your reply. I now understand your rationale.
