### ISSUE TITLE
integer field rendered as decimal 

### ISSUE THREAD

**Issue by jab3z** [michiya/django-pyodbc-azure#23]
Hi,

I'm connected remote to a mssql db using FreeTDS and I have a view with an IntegerField which is set as primary key due to django restrictions. The issue is the field value is not integer as it's supposed to be, but Decimal. Any idea why? And how I can fix this?

Regards,
Dacian

**Comment by whelks-chance** [comment]
Hi,

I am also having this issue, connecting to mssql using FreeTDS.

The primary_key is recognised by Django as being an AutoField, MSSQL sees it as being "numeric", and django-admin is trying to use a decimal in it's URLs.

ie instead of /object_thing/784/change, it shows /object_thing/784.0/change

Any ideas would be very welcome!

EDIT:

For future people finding this via Google, manually switching all the AutoFields to DecimalFields solved the problem.

**Comment by michiya** [comment]
Thank you for reporting.

I suppose the version of TDS protocol that you're running with is an obsolete one (v7.0 or earlier) and that's why you encounter the problem.

The backend assigns a `bigint` value to AutoField of a model object when it is newly created, but your SQL Server would automatically convert the data type of the value from `bigint` to `decimal` if you're running with an outdated version of the protocol which doesn't support the `bigint` type. More details about the supported data types among the versions of the protocol are described in:
http://www.freetds.org/userguide/choosingtdsprotocol.htm

You can specify the version of the protocol to work with using the `tds version` setting in your freetds.conf file, and you will be able to get rid of the problem if you choose the highest version of the protocol supported by your FreeTDS.

I've also made the fix for this issue (086da41) and it will be included in the next release of the backend, but note that the fix is just for AutoField values. You will encounter undesirable data type convesions of values again if you use BigIntegerFiled or DurationField in your models along with an obsolete version of TDS protocol.

I strongly recommend that you specify the highest version of the protocol you can choose in your freetds.conf file to obtain better support for modern SQL Server features.

**Comment by whelks-chance** [comment]
That was the problem! I actually changed to TDS 8.0 because I was getting unicode error messages for ntext and nvarchar fields - so I guess I've accidentally fixed the problem while solving a different one. I had experienced the BigIntegerField problem as well.

Sorry, I didn't realise version 8 was an option, I had copied the freetds.conf file from elsewhere on the internet, which I guess was outdated.

Thank you very much for your time, this all makes sense now.

**Comment by michiya** [comment]
Note that the fix is reverted in the v1.10 branch because BigAutoField is newly introduced and an id value can be an big integer in Django 1.10. Be sure to specify TDS version 7.1 or newer in your freetds.conf file when you work with Django 1.10.
