### ISSUE TITLE
Very minor issue: (lack of) compatibility with Micosoft ODBC Driver 11 for SQL Server for Linux

### ISSUE THREAD

**Issue by FlipperPA** [michiya/django-pyodbc-azure#28]
Re: "Compatible with SQL Server , SQL Server Native Client , <strong>Micosoft ODBC Driver 11 for SQL Server</strong> and FreeTDS ODBC drivers" on the README.

I've tested a fair amount of drivers against SQL Server 2008 through 2014 with Django. Since Django 1.7, the <strong>Micosoft ODBC Driver 11 for SQL Server</strong> has been problematic due to multithreading features introduced in Django 1.7.

To get runserver to come up, for example, I had to use the following option:

<code>./manage.py runserver --nothreading</code>

Additionally, other issues have cropped up, primary with "SQLRowCount returns 0" and SQLParam compatibility. More details here: http://stackoverflow.com/questions/28860521/large-select-query-hangs-using-python-and-unixodbc-connecting-to-sql-server

I've switched back to FreeTDS which is working like a charm. We may want to remove the language about supporting the MS ODBC driver on the README unless a solution has been found (I'm happy to issue a PR for the minor change).

Thanks for the great work, everyone.

**Comment by michiya** [comment]
Thank you for reporting.

As you know, the msodbcsql driver on Linux crashes in some cases and it doesn't support the latest Linux distributions. I hope Microsoft provide a new stable ODBC driver on Linux, but it haven't happened yet. So It would be better to suspend the support for the msodbcsql driver on Linux till a new stable one is available, 

I updated the document to show the backend only supports Microsoft ODBC Driver 11 for SQL Server **on Windows** instead of removing the driver name because the name `Microsoft ODBC Driver 11 for SQL Server` means the drivers both for Linux and for Windows.
https://technet.microsoft.com/en-us/library/jj730308(v=sql.110).aspx

**Comment by FlipperPA** [comment]
Thanks very much. Let me know if you ever want help with testing: I have access to SQL Server 2005 / 2008 / 2012 / 2014 in clustered environments, with branches set up in a Vagrant box for FreeTDS and the MS Linux driver on both Ubuntu and CentOS. While not quite unit testing, real-world examples can't hurt!

**Comment by meet-bhagdev** [comment]
Just a quick update on this, we have a new Linux ODBC driver in the pipeline. We plan on releasing it in the next 6-12 months. It will work on Ubuntu as well. 
@FlipperPA : I would love to connect with you to understand how you use Django with MSSQL

**Comment by FlipperPA** [comment]
@meet-bhagdev Fantastic news! I'm actually in Austin right now, about to depart DjangoCon, and met several people who are also using SQL Server with Django. I'd be happy to connect and provide you feedback! I'm @FlipperPA on Twitter (and pretty much everywhere).

**Comment by meet-bhagdev** [comment]
@FlipperPA : Great to hear. I am actually at DjangoCon too. I just tweeted at you. Hope to sync with you before you depart.
