### ISSUE TITLE
Getting started on Mac OS X Yosemite

### ISSUE THREAD

**Issue by meet-bhagdev** [michiya/django-pyodbc-azure#42]
Hello all,

I am trying to use this on my Mac machine and facing some trouble. Does anyone know how can i get started with a simple Django project based on this backend on my Mac.

I currently have FreeTDS and pyodbc installed in my machine. Is there anyway I can make this work without changing the config files for FreeTDS?

Cheers,
Meet

**Comment by shaib** [comment]
Hi Meet,
Can't help you with specifics because I'm not a Mac user and you haven't given much details about your setup or the problems you're facing. One thing which I had to tinker with, though, and you didn't mention at all, is unixODBC and its configuration. Specifically, I had to add an entry in /etc/odbcinst.ini for FreeTDS's ODBC driver.

Hope this helps,
Shai.

**Comment by reggieriser** [comment]
I'm using django-pyodbc-azure on Yosemite.  Here's what works for me...

Use [homebrew](http://brew.sh) to install unixodbc ("brew install unixodbc") and then install freetds with unixodbc support ("brew install freetds --with-unixodbc").  You'll probably want version 0.95 or later of freetds because it has support for SQL Server 2008 data types like "date" and "time".

Then, associate the driver name "FreeTDS" to the .so library by editing /usr/local/etc/odbcinst.ini and adding the following:

``` ini
[FreeTDS]
Description=FreeTDS Driver
Driver=/usr/local/lib/libtdsodbc.so
Setup=/usr/local/lib/libtdsodbc.so
FileUsage=1
```

Next, make sure your project has the appropriate version of django-pyodbc-azure for your desired Django version.  Installing django-pyodbc-azure should also bring in pyodbc.

Your DATABASES dictionary in settings.py could then look like this:

``` python
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'my_db_name',
        'USER': 'my_db_user',
        'PASSWORD': 'my_db_password',
        'HOST': 'myhost.company.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'FreeTDS',
            'host_is_server': True,
            'extra_params': 'TDS_VERSION=7.3',  # TDS 7.3 in freetds supports latest SQL Server 2008 types.
        }
    }
}
```

Tweak your DATABASES dictionary as needed for your environment.

**Note:** Given the above setup, I had to work around a problem in our app that I describe in issue #37.

**Comment by meet-bhagdev** [comment]
Thank you @shaib and @reggieriser ! Is there a way we can bypass the editing the odbcinst.ini?

**Comment by halfnibble** [comment]
@meet-bhagdev Yes! There is!

Instead of setting `'driver': 'FreeTDS',` set the property to the actual location of your driver.

In my case it was:
`'driver': '/usr/local/Cellar/freetds/0.95.80/lib/libtdsodbc.so',`

**Comment by yozik04** [comment]
if `pip install django-pyodbc-azure` gives you `fatal error: 'sql.h' file not found` during pyodbc installation

Then install pyodbc with next command
`pip install pyodbc --global-option=build_ext --global-option="-I/opt/local/include/" --global-option="-L/opt/local/lib/"`

probably next will also work
`pip install django-pyodbc-azure --global-option=build_ext --global-option="-I/opt/local/include/" --global-option="-L/opt/local/lib/"`
