### ISSUE TITLE
Cursor reuse causes 'Connection already closed' errors

### ISSUE THREAD

**Issue by dan-passaro** [michiya/django-pyodbc-azure#45]
I'm looking at this:

https://github.com/michiya/django-pyodbc-azure/blob/9e74bfd3f69b4946fd0a32f970e5d4d4e4e531cb/sql_server/pyodbc/base.py#L180

We experienced errors because another package we use, Cachalot, does a database introspection operation which triggers the Django framework to open and close a new cursor if one is not given to it. This is the core Django code:

```
def table_names(self, cursor=None, include_views=False):
    """
    Returns a list of names of all tables that exist in the database.
    The returned table list is sorted by Python's default sorting. We
    do NOT use database's ORDER BY here to avoid subtle differences
    in sorting order between databases.
    """
    def get_names(cursor):
        return sorted(ti.name for ti in self.get_table_list(cursor)
                      if include_views or ti.type == 't')
    if cursor is None:
        with self.connection.cursor() as cursor:
            return get_names(cursor)
    return get_names(cursor)
```

Due to the way that django-pyodbc-azure reuses cursors, this was causing a cursor in a totally different function to be closed prematurely.

I surveyed django-pyodbc as well as `django.db.backends.postgresql_psycopg2` and neither of these backends have this same cursor reuse logic. I don't understand all the layers of interacting libraries involved here, but it seems this is uncommon and perhaps buggy behavior in django-pyodbc-azure. I am going to fork and change this behavior; if you'd like a pull request please let me know!

And thank you so much for the work on this fantastic library, our upgrade to Django 1.8 is only possible thanks to your work updating django-pyodbc!! :)

**Comment by michiya** [comment]
@dan-passaro Thank you for the feedback.

FreeTDS doesn't support opening two different cursors and fetching data from them at the same time. You can't run the following code when you employ FreeTDS for example, and that's why the backend used to resue a cursor to prevent Django from opening multiple cursors on single connection via FreeTDS.

``` py
import pyodbc

conn = pyodbc.connect("DRIVER={FreeTDS};SERVERNAME=myserver;UID=sa;PWD=****;DATABASE=master")
cursor1 = conn.cursor()
cursor1.execute("select * from sys.tables")
cursor2 = conn.cursor()
cursor2.execute("select * from sys.indexes")
```

I agree with you that this behavior could be buggy in some cases, so I have updated the backend to allow opening multiple cursors without causing an error even in FreeTDS (cacef72) and published it on PyPI. I hope it will resolve your problem, and please let me know if you still have the same problem after updating the backend to the new one.

**Comment by dan-passaro** [comment]
Thank you @michiya. You were right; our underlying issue was the Cachalot package running a query in the midst of a different query, which doesn't work with FeeTDS on Linux. After the patch we found the underlying issue ("Cursor in invalid state") and were able to download and install the Microsoft ODBC driver for Linux to work around the issue. I really appreciate you taking the time to make the changes to allow the underlying issue to propagate, and again, thank you for keeping this library up to date. It's fantastic work!
