### ISSUE TITLE
Index not properly recreated on `Null` to `Not Null` migration

### ISSUE THREAD

**Issue by ashleyredzko** [michiya/django-pyodbc-azure#52]
When running migrations in Django 1.8, if a field is altered from being nullable to not allowing nulls, any indexes for it are not recreated or dropped, which causes an error. The exact error should look like below (with field names substituted):

```
django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The index '<INDEX_NAME>' is dependent on column '<COLUMN_NAME>'. (5074) (SQLExecDirectW)")
```

To work around this issue, we had to drop the index manually (using alter field and setitng `db_index` to `False`), alter the field to no longer be nullable, then alter the indexing back to true to create the index. This should, however, be handled by default.

---

**Old Migration:**

``` python
migrations.AlterField(
    model_name='<MODEL_NAME>',
    name='<FIELD_NAME>',
    field=models.ForeignKey(related_name='+', to='<RELATION_NAME>', null=False),
),
```

---

**New Migration:**

``` python
migrations.AlterField(
    model_name='<MODEL_NAME>',
    name='<FIELD_NAME>',
    field=models.ForeignKey(related_name='+', to='<RELATION_NAME>', null=True, db_index=False),
),
migrations.AlterField(
    model_name='<MODEL_NAME>',
    name='<FIELD_NAME>',
    field=models.ForeignKey(related_name='+', to='<RELATION_NAME>', null=False),
),
migrations.AlterField(
    model_name='<MODEL_NAME>',
    name='<FIELD_NAME>',
    field=models.ForeignKey(related_name='+', to='<RELATION_NAME>', null=False, db_index=True),
),
```

**Comment by kevin-brown** [comment]
Following up slightly further with this.

**The problem**

The issue occurs because you cannot change a column from NULL to NOT NULL when it has indexes that depend on it, which is why the error is explicitly pointing out at the index. This issue does not apply when going from `NOT NULL` to `NULL`, so this has the unfortunate side effect of either the forwards or reverse migration will work, but not both.

**Why it's happening**

After looking further, we confirmed this on Stack Overflow ([1](http://stackoverflow.com/q/25503975/359284), [2](http://stackoverflow.com/q/1258380/359284), [3](http://stackoverflow.com/q/2253185/359284)) as well as a couple of other places. And they all pretty much say that you need to drop the indexes, make the change, and then recreate the indexes if you need to change a column to NOT NULL. Currently the code just [makes the alter call](https://github.com/michiya/django-pyodbc-azure/blob/794f93ea4e882fc2ec48366fea1d02c3ce960073/sql_server/pyodbc/schema.py#L201-207) and that's it, so it will always fail in these cases (assuming there is an index attached). Our specific use case called for making a foreign key NOT NULL (`null=False`) that was previously NULL (`null=True`), but this should also apply to `unique=True` fields as well as fields which are manually indexed (`db_index=True`).

**The temporary fix**

The solution here was to drop the indexes on the column with `db_index=False`, make the `AlterField` change, and then add the indexes back. This is because `db_index=False` will [force the indexes to be dropped](https://github.com/michiya/django-pyodbc-azure/blob/794f93ea4e882fc2ec48366fea1d02c3ce960073/sql_server/pyodbc/schema.py#L104-L110) and `db_index=True` will [force them to be created again](https://github.com/michiya/django-pyodbc-azure/blob/794f93ea4e882fc2ec48366fea1d02c3ce960073/sql_server/pyodbc/schema.py#L257-L261). I have a hunch this isn't totally correct though, and we've yet to confirm that foreign keys are still set up properly.

**The suggested permanent fix**

When [making a column `NOT NULL`](https://github.com/michiya/django-pyodbc-azure/blob/794f93ea4e882fc2ec48366fea1d02c3ce960073/sql_server/pyodbc/schema.py#L201-207), the database indexes should be dropped ahead of time. The logic would be similar to what happens when [changing the type of a field](https://github.com/michiya/django-pyodbc-azure/blob/794f93ea4e882fc2ec48366fea1d02c3ce960073/sql_server/pyodbc/schema.py#L148-151).

**Comment by michiya** [comment]
@tredzko @kevin-brown Thank you for reporting! I've made the fix for this issue and will push it to PyPI as a part of the new version of the backend in the near future.

**Comment by michiya** [comment]
Closing the issue because the new version of the package that contains the fix is now available on PyPI. Feel free to open a new issue if you still have a problem.
