### ISSUE TITLE
How to add 'Application Name' (Program Name)

### ISSUE THREAD

**Issue by jonprasetyo** [michiya/django-pyodbc-azure#57]
How do we include the 'Application Name' or 'Program Name' into the settings?

We would like to view in our logs what application has accessed our database by executing the command sq_who2 and view the column 'Program Name'

Thank you

**Comment by daybarr** [comment]
Encode it in the `extra_params` key of `OPTIONS`, which is documented in README.md 

> Additional parameters for the ODBC connection. The format is  "param=value;param=value" .

``` python
DATABASES = {
    'default': {
        # ....
        'OPTIONS': {
            'extra_params': 'APP=MyApplicationName',
        },
    }
}
```

Remember that this is passed raw to ODBC, so if your application name is not hard coded and comes from untrusted input you'll need to take care to escape it, so attackers cannot set arbitrary parameters in your ODBC string. Since #39, django-pyodbc-azure gives you a function to do this escaping, like so:

``` python
from sql_server.pyodbc.base import encode_value

# ...

DATABASES = {
    'default': {
        # ....
        'OPTIONS': {
            'extra_params': 'APP=' + encode_value(some_untrusted_name),
        },
    }
}

```
