### ISSUE TITLE
SQL Server LocalDB support?

### ISSUE THREAD

**Issue by hermanocabral** [michiya/django-pyodbc-azure#68]
Anyone ever tried running SQLS LocalDB?

**Comment by michiya** [comment]
You can use SQL Server LocalDB with django-pyodbc-azure. I always use LocalDB for developing this backend because it's fast and handy. Here's an example of setting up:

1) Install LocalDB (and an ODBC driver if necessary)

2) Run the following commands as a Administrator

```
> sqllocaldb create SQLLOCAL
> sqllocaldb share SQLLOCAL SQLLOCALSHARED
> sqllocaldb start SQLLOCAL
> sqllocaldb info SQLLOCAL
> sqlcmd -S (named pipe name described in the info command above)
1> create login mydjangouser with password='password'
2> go
1> sp_addsrvrolemember mydjangouser, sysadmin
2> go
1> create user mydjangouser
2> go
1> create database mydb
2> go
1> exit
```

3) Update DATABASES settings for your Django app

``` py
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'mydb',
        'USER': 'mydjangouser',
        'PASSWORD': 'password',
        'HOST': '(localdb)\\.\\SQLLOCALSHARED',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 11 for SQL Server',
        },
    },
}
```

Note that you can't connect to LocalDB with Microsoft ODBC Driver 13 (Preview) for SQL Server on Windows as of writing. I'm using Microsoft ODBC Driver 11 to connect to SQL Server 2016 LocalDB now as a workaround. I hope the issue would be resolved by Microsoft in the future.
