### ISSUE TITLE
DB connection string

### ISSUE THREAD

**Issue by rosiecakes** [michiya/django-pyodbc-azure#89]
Hi! First off thanks for maintaining this, it's the only thing I got to work with Django & our legacy db environment and it works well. 

I'm looking to implement django-environ for production and with what I've read about it so far (admittedly not too much) it uses a URL for the db connection. Could you help me figure out what the syntax would be for this? I have tried every combination I could come up with and read [here](https://github.com/mkleehammer/pyodbc/wiki/Connection) and [here](https://gist.github.com/rduplain/1293636) among many, many others, and I'm sure I'm just missing something about this implementation. 

> Django==1.10.5
> django-pyodbc-azure==1.10.4.0
> pyodbc==4.0.1

```
DATABASES = {
    'default': {
        'ENGINE': "sql_server.pyodbc",
        'HOST': "<machine ip>,1433",
        'USER': "domain\user",
        'PASSWORD': "password",
        'NAME': "dbname",
        'OPTIONS': {
           'host_is_server': True
        }
    }
}
```

**Comment by kevin-brown** [comment]
django-environ does not support ODBC/MSSQL for database URLs: https://django-environ.readthedocs.io/en/latest/#supported-types

You would need to patch their `DB_SCHEMES` setup in order to get that working: https://github.com/joke2k/django-environ/blob/b1d9b6eedc0e6d578cc96682a9ecd41cef0a7872/environ/environ.py#L71

Once you added a new scheme, it _should_ work without any extra help. Just like how you'd configure the other databases.

**Comment by rosiecakes** [comment]
oh wow! weird that they have so many others and not mssql. I should've scoured their source code first, sorry about that! Thanks for the reply
